apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fake-service
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      labels:
        app: fake-service
    spec:
      containers:
      - name: fake-service
        image: traefik/whoami:latest
        env:
        - name: VERSION
          value: "v1.0.0"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 10s
      - setWeight: 100
